export const COLOR_TERMS: Record<string, string> = {
  kirmizi: "kırmızı",
  kırmız: "kırmızı",
  kirmiz: "kırmızı",
  kırmızı: "kırmızı",
  al: "kırmızı",
  bordo: "kırmızı",
  beyaz: "beyaz",
  siyah: "siyah",
  kara: "siyah",
  mavi: "mavi",
  lacivert: "mavi",
  yesil: "yeşil",
  yeşil: "yeşil",
  sari: "sarı",
  sarı: "sarı",
  mor: "mor",
  pembe: "pembe",
  turuncu: "turuncu",
  gri: "gri",
  kahverengi: "kahverengi",
  kahve: "kahverengi",
  altin: "altın",
  altın: "altın",
  gumus: "gümüş",
  gümüş: "gümüş",
};

export const ACTION_TERMS: Record<string, string> = {
  gormek: "görmek",
  almak: "almak",
  satin: "almak",
  satmak: "satmak",
  bulmak: "bulmak",
  kaybetmek: "kaybetmek",
  kaybet: "kaybetmek",
  calmak: "çalmak",
  calinmak: "çalınmak",
  vermek: "vermek",
  kirmak: "kırmak",
  kirilmak: "kırılmak",
  yikamak: "yıkamak",
  temizlemek: "temizlemek",
  yakmak: "yakmak",
  yanmak: "yanmak",
  kosmak: "koşmak",
  kacmak: "kaçmak",
  kovalamak: "kovalamak",
  kovalanmak: "kovalanmak",
  dusmek: "düşmek",
  ucmak: "uçmak",
  tirmanmak: "tırmanmak",
  inmek: "inmek",
  cikmak: "çıkmak",
  yuzmek: "yüzmek",
  bogulmak: "boğulmak",
  sarilmak: "sarılmak",
  opusmek: "öpüşmek",
  kavga: "kavga etmek",
  bagirmak: "bağırmak",
  aglamak: "ağlamak",
  gulmek: "gülmek",
  uyumak: "uyumak",
  uyanmak: "uyanmak",
  konusmak: "konuşmak",
  susmak: "susmak",
  saklanmak: "saklanmak",
  beklemek: "beklemek",
  aramak: "aramak",
  oldurmek: "öldürmek",
  kurtarmak: "kurtarmak",
  surmek: "sürmek",
  kullanmak: "sürmek",
  binmek: "binmek",
  giymek: "giymek",
  yemek: "yemek",
  pisirmek: "pişirmek",
  emzirmek: "emzirmek",
  dogurmak: "doğurmak",
  sevmek: "sevmek",
};

export const GENDER_TERMS: Record<string, string> = {
  erkek: "erkek",
  kiz: "kız",
  kız: "kız",
  kadin: "kadın",
  kadın: "kadın",
};

export const SYNONYMS: Record<string, string> = {
  otomobil: "araba",
  binek: "araba",
  arac: "araba",
  bebegin: "bebek",
  yavru: "bebek",
  motosiklet: "motor",
  motorsiklet: "motor",
  cep: "telefon",
  ceptelefonu: "telefon",
  telefonu: "telefon",
  ex: "eski sevgili",
  eskiask: "eski sevgili",
  eskierkekarkadas: "eski sevgili",
  eskikizarkadas: "eski sevgili",
  kaynana: "kayınvalide",
  kayinvalide: "kayınvalide",
  kayinpeder: "kayınpeder",
  insta: "instagram",
  whatsapp: "whatsapp",
  wp: "whatsapp",
  hastahane: "hastane",
  isyeri: "iş yeri",
  isyer: "iş yeri",
  anahtarlik: "anahtar",
  cantam: "çanta",
  canta: "çanta",
  valiz: "valiz",
  bavul: "valiz",
  askerlik: "asker",
  uniforma: "üniforma",
};

export function colorMeaningLine(color: string) {
  const lines: Record<string, string> = {
    kırmızı: "Kırmızı, henüz sönmemiş bir yaşam kuvvetini ve görünür bir çekimi boyar.",
    beyaz: "Beyaz, arınma, uğurlama ve net bir başlangıç örtüsü taşır.",
    siyah: "Siyah, gizli, ağır veya henüz adlandırılmamış bir katmanı örter.",
    mavi: "Mavi, mesafe, sükûnet ve sözün yavaşlamasını taşır.",
    yeşil: "Yeşil, onarım, büyüme ve tazelenen bir hattı boyar.",
    sarı: "Sarı, dikkat, zihin ışıması ve görünür bir uyarı taşıyabilir.",
    mor: "Mor, eşik, sezgi ve görünmez katmanın açıldığını duyurur.",
    pembe: "Pembe, yumuşak bağ ve şefkat ihtiyacını boyar.",
    turuncu: "Turuncu, hareket, cesaret ve ısınan bir alanı taşır.",
    gri: "Gri, belirsizlik ve ara eşikte bekleyen enerjiyi örter.",
    kahverengi: "Kahverengi, kök, madde ve dünyevi zemini hatırlatır.",
    altın: "Altın, değer, kutsallık ve seçilmiş bir kuvveti parlatır.",
    gümüş: "Gümüş, ay hattı, sezgi ve yansıyan bir netliği taşır.",
  };
  return lines[color] ?? "";
}

export function actionMeaningLine(action: string) {
  const lines: Record<string, string> = {
    sürmek: "Sürmek, yönün senin elinde olduğunu ve tempo seçimini konuşur.",
    binmek: "Binmek, bir yola dahil oluşu ve taşıyıcı kuvvete teslimi anlatır.",
    giymek: "Giymek, kimliği üzerine almak ve görünür hale getirmek demektir.",
    kaybetmek: "Kaybetmek, o sembolün temsil ettiği hattın elinden kaydığını gösterir.",
    çalınmak: "Çalınmak, irade dışı bir kayıp ve sınır ihlalini taşır.",
    kırmak: "Kırmak, eski bir kalıbı bilinçli veya ani biçimde sonlandırmaktır.",
    yemek: "Yemek, o kuvveti içeri almak ve özümsemek demektir.",
    emzirmek: "Emzirmek, doğmakta olanı beslemek ve sorumluluk hattını açar.",
    doğurmak: "Doğurmak, bir özün alana çıkışını ve yeni bir çevrimin başını taşır.",
    kaçmak: "Kaçmak, henüz durulamayan bir alandan çıkış refleksini gösterir.",
    düşmek: "Düşmek, zemin kaybı ve kontrolün el değiştirdiği eşiği anlatır.",
  };
  return lines[action] ?? "";
}
